### ISSUE TITLE
Parametros GAMECARD

### ISSUE THREAD

**Issue by Nico9813** [sisoputnfrba/delibird-pruebas#1]
Buenas, estabamos corriendo los test y vimos que los parametros que mandan cuando consultan a la gamecard no son los mismos que los indicados en la consigna.

![image](https://user-images.githubusercontent.com/30988717/84462285-03852600-ac45-11ea-98df-a8520ffca937.png)

Esto pasa en los archivos 
- new_pikachu.sh
- new_pokemons_varios.sh
- catch_charmander.sh

En todos falta el id de mensaje al final.

**Comment by Zheoden** [comment]
No vimos este issue antes, pero esta solucionado hace un tiempo esto, asi que cierro el issue. Gracias por avisarnos!
