### ISSUE TITLE
Envio de mensaje NEW_POKEMON a Team en espera_circular_basico.sh

### ISSUE THREAD

**Issue by leobz** [sisoputnfrba/delibird-pruebas#2]
Creo que el Gameboy debería enviar un APPEARED_POKEMON en vez de NEW_POKEMON, ya que el Team no entiende el mensaje New. Quizás me estoy equivocando pero bueno, por las dudas subo el issue!

https://github.com/sisoputnfrba/delibird-pruebas/blob/1d041f2519dee9f2c33568827ca8852ff55c2803/espera_circular_basico.sh#L2

**Comment by Zheoden** [comment]
Ya quedo fixeado, fue un error nuestro, gracias!
